version: '3.4'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - "./backend:/app"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - "./frontend:/app"

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learnalanguage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5