name: Automated Testing on commit

on:
  push:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install modules
        working-directory: frontend
        run: npm ci
      - name: Run ESLint
        working-directory: frontend
        run: npm run lint:prod
      - name: Run tsx
        working-directory: frontend
        run: npx tsc --noEmit --noErrorTruncation
